services:
  bcx-cms-api:
    image: bcx-cms-api
    container_name: bcx-cms-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000