name: CI with GCP

on:
  push:
    branches:
      - develop
      - main
env:
  GCP_PROJECT_ID: banchanxanh
  GCP_REGION: us-central1
  GKE_CLUSTER: bcx-cluster
  GKE_REGION: us-central1-a
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: "latest" # Or a specific version
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Determine Build value
        id: build_value
        run: |
          ENVIRONMENT=""
          REPOSITORY_NAME=$(echo '${{ github.repository }}' | cut -d '/' -f 2)

          if [ "$BRANCH_NAME" == "main" ]; then
            ENVIRONMENT="prod"
            echo "DEPLOYMENT_NAME=$REPOSITORY_NAME-prod" >> $GITHUB_OUTPUT
          else
            ENVIRONMENT="develop"
            echo "DEPLOYMENT_NAME=$REPOSITORY_NAME-dev" >> $GITHUB_OUTPUT
          fi

          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> $GITHUB_OUTPUT

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker Image and Push to GCP Artifact Registry
        id: build_push
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          VERSION=$(jq -r .version package.json)
          BUILD_IMAGE=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ steps.build_value.outputs.ENVIRONMENT }}/${{ steps.build_value.outputs.REPOSITORY_NAME }}-$VERSION:$TIMESTAMP
          echo "Building image: $BUILD_IMAGE"  # Debugging
          docker buildx create --use
          docker buildx build --push -t "${BUILD_IMAGE}" . --file Dockerfile.prod --platform linux/amd64
          echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_OUTPUT #export build image for later use

      - name: Get runner public IP
        id: ip
        run: |
          echo "ip=$(curl -s https://checkip.amazonaws.com)/32" >> "$GITHUB_OUTPUT"
          
      - name: Allow runner IP
        run: |
          gcloud container clusters update 'bcx-cluster' \
            --region 'us-central1-a' \
            --project 'banchanxanh' \
            --enable-master-authorized-networks \
            --master-authorized-networks "10.239.0.0/24,133.32.216.3/32,${{ steps.ip.outputs.ip }}"
            
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/${{ steps.build_value.outputs.DEPLOYMENT_NAME }} ${{ steps.build_value.outputs.REPOSITORY_NAME }}=${{ steps.build_push.outputs.BUILD_IMAGE }}

      - name: Wait for Deployment Rollout
        run: |
          kubectl rollout restart deployment/${{ steps.build_value.outputs.DEPLOYMENT_NAME }}
